<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-0PBS36T" name="a1.RestAssured.REQRESTests" tests="7" failures="1" timestamp="2 Jan 2021 12:06:36 GMT" time="8.583" errors="0">
  <testcase name="createUser" time="5.066" classname="a1.RestAssured.REQRESTests"/>
  <testcase name="listUsersInaPage" time="0.516" classname="a1.RestAssured.REQRESTests"/>
  <testcase name="listSingleUser" time="0.522" classname="a1.RestAssured.REQRESTests"/>
  <testcase name="userNotFound" time="0.335" classname="a1.RestAssured.REQRESTests">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 404 Not Found] but found [HTTP/1.1 200 OK]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 404 Not Found] but found [HTTP/1.1 200 OK]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at a1.RestAssured.REQRESTests.userNotFound(REQRESTests.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- userNotFound -->
  <testcase name="login" time="0.502" classname="a1.RestAssured.REQRESTests"/>
  <testcase name="deleteUsers" time="1.117" classname="a1.RestAssured.REQRESTests"/>
  <testcase name="updateUserRole" time="0.525" classname="a1.RestAssured.REQRESTests"/>
</testsuite> <!-- a1.RestAssured.REQRESTests -->
